replicaCount: 1
image:
  repository: my-rails-dev
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  internalPort: 3000

databaseType:
  postgresql: true
postgresql:
  image: my-postgresql-dev
  imageTag: latest
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
    existingClaim: app-workdir-pvc
    subPath: ".data/postgresql"
