web:
  replicasCount: 2
  image:
    repository: my-rails-dev
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    internalPort: 3000

databaseType:
  postgresql: true
postgresql-dev:
  image: my-postgresql-dev
  imageTag: latest
  imagePullPolicy: IfNotPresent
  postgresDatabase: dev
  postgresPassword: password
  persistence:
    enabled: true
    existingClaim: app-workdir-pvc
    subPath: ".data/postgresql"
postgresql-test:
  image: my-postgresql-dev
  imageTag: latest
  imagePullPolicy: IfNotPresent
  postgresDatabase: test
  postgresPassword: password
  persistence:
    enabled: false

volumes:
  appdir: "/app"
