kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "helm-rails.fullname" . }}
  labels:
    app: {{ template "helm-rails.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: {{ template "helm-rails.fullname" . }}
