apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "helm-rails.fullname" . }}
  labels:
    app: {{ template "helm-rails.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/app"