apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "helm-rails.fullname" . }}
  labels:
    app: {{ template "helm-rails.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicasCount }}
  template:
    metadata:
      labels:
        app: {{ template "helm-rails.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
          - name: DATABASE_URL
            value: "postgres://postgres:password@my-rails-dev-postgresql-dev/dev"
          volumeMounts:
            - name: app-workdir
              mountPath: "/service"
          command: ["/bin/sh"]
          args: ["-c", "rails db:migrate"]
        - name: {{ .Chart.Name }}-pidfiles-cleanup
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          command: ['sh', '-c', 'rm -f tmp/pids/*']
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:password@my-rails-dev-postgresql-dev/dev"
        ports:
        - containerPort: {{ .Values.web.service.internalPort }}
        volumeMounts:
        - name: app-workdir
          mountPath: "/service"
        command: ["/bin/sh"]
        args: ["-c", "cat tmp/pids/server.pid && rm -f tmp/pids/server.pid || true && rails server -b 0.0.0.0 -p {{ .Values.web.service.internalPort }}"]
      volumes:
        - name: app-workdir
          persistentVolumeClaim:
            claimName: app-workdir-pvc
